#!/usr/bin/env python

"""
########################################################################
# Author:       Carlos A. Ruiz Perez
# Email:        cruizperez3@gatech.edu
# Intitution:   Georgia Institute of Technology
# Version:      0.9
# Date:         March 04, 2020

# Description: Create SQLite database from a tab-delimited table.
Used to create annotation parsing databases.
########################################################################
"""

################################################################################
"""---0.0 Import Modules---"""
import sqlite3
import csv
import re
from sys import exit
import pandas as pd
from sqlalchemy import create_engine
from shutil import which
import subprocess
from pathlib import Path

################################################################################
"""---1.0 Define Functions---"""
def create_sql_table_slow(database, input_table):
    """ Creates a SQLite database using a tab-delimited table as input
    
    Arguments:
        database {string} -- New or existing database to create table into
        input_table {string} -- Table to parse and transform to SQLite db
    """
    print("Checking table and column names... ", end="")
    column_names = []
    with open(input_table) as intable:
        column_names = intable.readline().split("\t")
    table_name = str(Path(input_table).with_suffix(""))
    if check_table_name(table_name) == False:
        exit("Input table name should only be composed of alphanumeric characters and underscores")
    for column in column_names:
        if check_table_name(table_name) == False:
            exit("Column {} should only be composed of \
                alphanumeric characters and underscores".format(column))
    print("Done. Everything seems good.")

    # Read input table and populate database
    print("Creating and populating database... ", end="", flush=True)
    engine = create_engine('sqlite:///'+database, echo=False)
    connection = engine.connect()
    for table_chunk in pd.read_csv(input_table, sep="\t", chunksize=1000000, header=0):
        table_chunk.to_sql(table_name, con=engine, if_exists='replace', index=False)
    connection.close()
    # Create index
    conn = sqlite3.connect(database)
    conn.text_factory = str
    cursor = conn.cursor()
    sql_comm = 'CREATE INDEX protein_id on %s (%s)' % (table_name, column_names[0])
    cursor.execute(sql_comm)
    conn.commit()
    cursor.close()
    conn.close()
    print("Done")

def create_sql_table_fast(database, input_table):
    """ Creates a SQLite database using a tab-delimited table as input
    
    Arguments:
        database {string} -- Name of a new or existing database
        input_table {string} -- Tab-separated table to use as template
    """
    print("Checking table and column names... ", end="")
    column_names = []
    with open(input_table) as intable:
        column_names = intable.readline().split("\t")
    table_name = str(Path(input_table).with_suffix(""))
    if check_table_name(table_name) == False:
        exit("Input table name should only be composed of alphanumeric characters and underscores")
    for column in column_names:
        if check_table_name(table_name) == False:
            exit("Column {} should only be composed of \
                alphanumeric characters and underscores".format(column))
    print("Done. Everything seems good.")

    print("Creating and populating database... ", end="", flush=True)
    subprocess.call(["csv-to-sqlite", "-f", str(input_table), "-o", str(database), 
                    "-t", "none", "-D", "-x", "\t"])
    conn = sqlite3.connect(database)
    conn.text_factory = str
    cursor = conn.cursor()
    sql_comm = 'CREATE INDEX protein_id on %s (%s)' % (table_name, column_names[0])
    cursor.execute(sql_comm)
    conn.commit()
    cursor.close()
    conn.close()
    print("Done")


def check_table_name(name_string):
    """ Checks if string contains any non alpha-numeric
        or underscores characters.
    
    Arguments:
        name_string {string} -- String to evaluate
    
    Returns:
        approved {bool} -- Boolean evaluating if string passes test or not
    """
    approved = True
    for character in name_string:
        if not re.match(r'[A-Za-z0-9_]+', character):
            approved = False
            break
    return approved


################################################################################
"""---3.0 Main Function---"""

def main():
    import argparse, sys
    # Setup parser for arguments.
    parser = argparse.ArgumentParser(formatter_class=argparse.RawTextHelpFormatter,
            description='''This script builds a sqlite database from a tab separated table.\n'''
            '''By default it assumes the first line of the input table has headers, if not\n'''
            '''you must provide a list of headers as --header header1,header2,header3...\n'''
            '''Usage: ''' + sys.argv[0] + ''' -i [Input Table] -d [Database Name]\n'''
            '''Global mandatory parameters: -i [Input Table] -d [Database Name]\n'''
            '''Optional Database Parameters: See ''' + sys.argv[0] + ' -h')
    parser.add_argument('-i', '--input', dest='input_table', action='store', required=True,
                        help='Input tab-delimited table to parse, by default assumes headers are present')
    parser.add_argument('-d', '--database', dest='database', action='store', required=True,
                        help='Database name, can be exisiting or new.')
    args = parser.parse_args()

    input_table = args.input_table
    database = args.database

    # ----------------------------
    if which("csv-to-sqlite") is not None:
        print("Running fast database builder")
        create_sql_table_fast(database, input_table)
    else:
        print("csv-to-sqlite not found. You can run the slow approach or\n \
        install csv-to-sqlite with 'pip install csv-to-sqlite'.")
        decision = input("Continue [yes/no]? ").lower()
        if decision == 'yes':
            create_sql_table_slow(database, input_table)
        else:
            exit("Bye!")
    print("Database succesfully created!")
    # ----------------------------

if __name__ == "__main__":
    main()
